playerOptions:
  deafenOnJoin: true
  leaveOnEmpty: true
  leaveOnEnd: true
  leaveOnStop: true
  quality: high
  timeout: 10000
  volume: 100
commandOptions:
  play:
    description: Search for a song to play.
messages:
  embedColor: "#de111e"
  errorEmbedColor: "#de111e"
