bigNowPlayingThumbnails: false
bigSearchResultThumbnails: true
playerOptions:
  autoSelfDeaf: true
  initialVolume: 100
  leaveOnEmpty: true
  leaveOnStop: true
  leaveOnEnd: true
  leaveOnEmptyCooldown: 60000
  spotifyBridge: true
  ytdlOptions: {}
commandOptions:
  play:
    description: Search for a song to play.
messages:
  embedColor: "#de111e"
  errorEmbedColor: "#de111e"
  loading: Loading...
  noSearchQueryProvided: Enter a search query.
  noResultsFound: No results found.
  notInGuild: You are not in a guild.
  notInVoiceChannel: You are not in a voice channel.
  notInBotVoiceChannel: You are not in the voice channel I'm in.
  cantConnectToVoiceChannel: description:Can't connect to {0}
  botInternalError: An error occurred
  commandCooldown: description:Wait for `{0}` cooldown.
  commandError: An error occurred while executing this command.
  commandInvalidArguments: "description:Invalid arguments given to option(s): {0}"
  commandMissingArguments: "description:Missing required command arguments: {0}"
  commandNoBotPermissions: I don't have enough permissions to execute this command.
  commandNoMemberPermissions: You do not have enough permissions to execute this command.
